name: Test GitLab Pipeline

on:
  pull_request:
    paths:
      - '{{cookiecutter.project_slug}}/Makefile'
      - '{{cookiecutter.project_slug}}/.gitlab-ci.yml'

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make setup-cicd-pipelines-tests
      - name: Run GitLab pipeline test
        env:
          PIPELINE_GIT_NAME: ${{ secrets.PIPELINE_GIT_NAME }}
          PIPELINE_GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.PIPELINE_GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.PIPELINE_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.PIPELINE_GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.PIPELINE_GIT_EMAIL }}
        run: make test-gitlab-pipeline
